### PR TITLE
Add requirements to blocked scenario

### PR DESCRIPTION
**Pull request by venkatd**

### CODE REVIEW

**Comment by venkatd** [comment]
@JoshSmith what should happen when someone is blocked? I'm I'm thinking they create a comment in Asana referencing who they are blocked by and describe exactly what they need from them. Then they should assign the Asana task to them.

**Comment by joshsmith** [comment]
The problem with reassigning a task is that it could be meaningless to the person who's blocking. I think the process should look more like:
- Your task is blocked. Mark it with `blocked`.
- Create an explicit task for the person who's blocking it with a clear description of what task they're blocking (using @task autocompletion) and what the acceptance criteria is for unblocking your task.
- Comment @whomever inside of your original saying this task is blocked by the new task name (using @task autocompletion).
- ???

I don't know what the next best step is for informing the person that their task is unblocked. I think it's up to the person who added `blocked` to remove that tag.

**Comment by venkatd** [comment]
Yeah we can also reference the tasks you are blocked by like so:

image

This way when a PM or someone is like, wait why are you blocked? They'll have links to all the tasks of people they need to prod.

**Comment by joshsmith** [comment]
Yeah, I agree.

What do you think about my ??? uncertainty?

**Comment by venkatd** [comment]
Once the person who has given the blocked person what they need:
- Reference the person in the comment of the blocked task saying they should be unblocked
- Person who is blocked should remove the blocked tag

The question is whose responsibility is it to remove the blocked tag?

**Comment by joshsmith** [comment]
I think it's the responsibility of the person who placed the blocked tag to remove it. They're the ones who set the acceptance criteria for it becoming blocked, so they should be the ones to accept it as unblocked.

**Comment by venkatd** [comment]
Agreed.

**Pull request closed without merging**
